using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HamHam.Application.Interfaces;
using HamHam.Domain.Entities;
using HamHam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace HamHam.Infrastructure.Services
{
    public class BookmarkImportService : IBookmarkImportService
    {
        private readonly HamHamDbContext _context;

        public BookmarkImportService(HamHamDbContext context)
        {
            _context = context;
        }

        public async Task<bool> ImportPublicBookmarksAsync(string userId, List<string> publicBookmarkIds, string targetCategoryId, string color, bool glass)
        {
            try
            {
                var userGuid = Guid.Parse(userId);
                var categoryGuid = Guid.Parse(targetCategoryId);

                // 1. Validate that the target category exists and belongs to the user
                var category = await _context.Categories
                    .FirstOrDefaultAsync(c => c.Id == categoryGuid && c.UsersId == userGuid);

                if (category == null)
                {
                    Console.WriteLine($"[BookmarkImportService] Invalid category {targetCategoryId} for user {userId}");
                    return false;
                }

                // 2. Fetch the public bookmarks to be cloned
                var publicBookmarks = await _context.SharedPoolBookmarks
                    .Where(b => publicBookmarkIds.Contains(b.Id.ToString()))
                    .ToListAsync();

                if (!publicBookmarks.Any()) return false;

                // 3. Determine the sort order for new bookmarks
                var lastSortOrder = await _context.Bookmarks
                    .Where(b => b.CategoriesId == categoryGuid)
                    .OrderByDescending(b => b.SortOrder)
                    .Select(b => (int?)b.SortOrder)
                    .FirstOrDefaultAsync() ?? -1;

                // 4. Clone the bookmarks
                var newBookmarks = publicBookmarks.Select((pb, index) => new Bookmark
                {
                    UsersId = userGuid,
                    CategoriesId = categoryGuid,
                    Title = pb.Name,
                    Subtitle = "", // SharedPoolBookmark doesn't have a subtitle
                    Url = pb.Url,
                    Color = glass ? "glass" : color,
                    SortOrder = lastSortOrder + index + 1,
                    FaviconUrl = "", // Will be generated by the system or handled separately
                    IsFavorite = false
                }).ToList();

                _context.Bookmarks.AddRange(newBookmarks);
                await _context.SaveChangesAsync();

                return true;
            }
            catch (Exception ex)
            {
                // Log exception
                Console.WriteLine($"[BookmarkImportService] Error importing bookmarks: {ex.Message}");
                return false;
            }
        }
    }
}

